### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by davidw** [johanvts/emacs-fireplace#10]
I just see a solid red buffer with no actual fire.

Adding smoke makes the top of the fire visible.

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.6) of 2015-09-17 on lgw01-52, modified by Debian

**Comment by w1gz** [comment]
Same issue (with the smoke trick too) on `GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.17.8) of 2015-09-11 on buildvm-21.phx2.fedoraproject.org`

**Comment by johanvts** [comment]
Thanks. I saw some comments that ''visual-line-mode'' or ''truncate-lines'' might break the fireplace. Can you try flipping those and checking if that helps?

**Comment by w1gz** [comment]
Ok, you're on to something @johanvts. I did try visual+truncate but they were already off. So I basically disabled my .emacs and the fireplace was working !

To help others, my naughty line was : `(setq-default show-trailing-whitespace t)`.

I can now enjoy a nice fire, thanks to you @johanvts.

**Comment by thomas-louvigne** [comment]
Still have a bug ...
Any idea ?

![img](http://i.imgur.com/9mKn74O.png)

**Comment by w1gz** [comment]
@zobi8225 remove your .emacs entirely and retry the fireplace. I'm pretty sure it's not the Emacs version that is at fault but an incompatibility with an extension, plugin or configuration set in your .emacs

**Comment by thomas-louvigne** [comment]
@w1gz Yea, i am sure it is a .emacs problem, but where is the problem...

**Comment by davidw** [comment]
For me the problem was `show-trailing-whitespace`.  I suppose this should turn that off locally.

**Comment by w1gz** [comment]
@zobi8225 If you're lost or can't figure it out, just gradually comment/uncomment your .emacs (dichotomy helps here!)

**Comment by johanvts** [comment]
I renamed the issue since it broadened a bit. I think some of the settings could be overridden on a pr. buffer basis to avoid people seeing these errors. I will add that tast to the todo list.

**Comment by thomas-louvigne** [comment]
I have commented this lines and it's better (but not perfect...)

> ;; (setq-default show-trailing-whitespace t)  
> ;; (setq-default show-leading-whitespace t)  
> ;; (setq-default indicate-empty-lines t)   

![Image of fireplace](http://i.imgur.com/BKowyMU.png)

**Comment by jaxspades** [comment]
I have the same issue with the above screenshot. I think it doesn't like line numbers. :)

Or rather, line numbers don't like it. I have various buffers, including Org mode ones, that have issues with line numbers.

**Comment by AdrieanKhisbe** [comment]
I just pushed a fix 1ba1234 that should take care of these rendering issues.
It has been released under 1.1.1, and will be on melpa next build.

@zobi8225 @jaxspades @davidw @w1gz could you tell me if it works for you?

**Comment by w1gz** [comment]
@AdrieanKhisbe fresh from MELPA and working perfectly :). Thank you.

**Comment by AdrieanKhisbe** [comment]
you're welcome :)
closing the issue then!

**Comment by thomas-louvigne** [comment]
@AdrieanKhisbe : Yes ! Now it works !
Thx !

**Comment by AdrieanKhisbe** [comment]
:fire_engine: :wink:
