### ISSUE TITLE
rendering problem

### ISSUE THREAD

**Issue by nikolas** [johanvts/emacs-fireplace#18]
My fireplace looks like this:
![2015-12-20-080508_680x765_scrot](https://cloud.githubusercontent.com/assets/59292/11918084/72b88d46-a6f0-11e5-8fe1-1f044384e1e8.png)

Maybe a bug.

I have emacs 24.5.50.1 compiled with GTK+ 2.24.23.

**Comment by johanvts** [comment]
Did you try the solutions from https://github.com/johanvts/emacs-fireplace/issues/10 ?
