### ISSUE TITLE
Issues with window size changing

### ISSUE THREAD

**Issue by wiruzx** [johanvts/emacs-fireplace#20]
In some cases fire is showing perfectly:

![](http://i.imgur.com/CQgfaBO.png)

But if I change the window size a little bit, it starting showing above the status line

![](http://i.imgur.com/z4YK9Wk.png)

Or started showing line breaks:

![](http://i.imgur.com/uSt82uE.png)

**Comment by johanvts** [comment]
The fireplace attempts to fill the window when it's started, but it does not currently change size if the window size is changed afterwards. You should be able to work around this issue by restarting the fire after adjusting the window. I will add dynamic scaling to the to-do list.
