### ISSUE TITLE
Calling fireplace causes: redisplay_internal (C function): Wrong number of arguments: (0 . 0), 1 Message

### ISSUE THREAD

**Issue by sshaw** [johanvts/emacs-fireplace#22]
The fireplace is still shown. `emacs-version`:

```
GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-18 on builder10-9.porkrind.org
```

**Comment by AdrieanKhisbe** [comment]
Thanks to report it.
I have some idea what could be behid that.
Gonna dig in the days to come when I have tiem :)

**Comment by johanvts** [comment]
I get this error too, but at the same time the fire is drawn way to narrow. Like only half width of the actual buffer.

EDIT: Looked into it a bit and seems to be some setting of mine causing the width issue. But the error is there in emacs -q
