### ISSUE TITLE
The fire does not extinguish with kill-buffer and undo history grows indefinitely

### ISSUE THREAD

**Issue by varjagg** [johanvts/emacs-fireplace#3]
Emacs then complains

Warning (undo): Buffer `*fireplace*' undo info was 13108363 bytes long.
The undo info was discarded because it exceeded`undo-outer-limit'.

This is normal if you executed a command that made a huge change
to the buffer.  In that case, to prevent similar problems in the
future, set `undo-outer-limit' to a value that is large enough to
cover the maximum size of normal changes you expect a single
command to make, but not so large that it might exceed the
maximum memory allotted to Emacs.

If you did not execute any such command, the situation is
probably due to a bug and you should report it.

You can disable the popping up of this buffer by adding the entry
(undo discard-info) to the user option `warning-suppress-types',
which is defined in the`warnings' library.

**Comment by johanvts** [comment]
Only ''fireplace-off'' is supported for now. I will add supporting ''kill-buffer'' to the todo list.
Buffer-undo should be disabled, do you have any hooks on special-mode that might have re-enabled buffer undo?

**Comment by AdrieanKhisbe** [comment]
fixed with #16
