### ISSUE TITLE
Can't get sound working

### ISSUE THREAD

**Issue by MElemental** [johanvts/emacs-fireplace#32]
I can't seem to get the sound working on the fireplace. I'm on spacemacs.
when I try to do `M-x fireplace-toggle-sound` or `C-=` I get no sound.

This appears in my message buffer, but it might be a red herring to the sound issue.
````
Error during redisplay: (fireplace--update-locals-vars #<window 3 on *fireplace*>) signaled (wrong-number-of-arguments (0 . 0) 1)
````

I'm not sure what the issue is. I did try to explicitly set the variable `fireplace-sound-file-path` but still have no sound. I tested out the ffplay command in the terminal, and that works.

I initially thought that MELPA wasn't downloading the mp3 so I tried to switch to the github repo.

**Comment by MElemental** [comment]
I managed to fix it. I managed to change to the location to the repo and avoid directly relabeling the sound file path variable.

**Comment by bnsv** [comment]
Mine also has no sound. I check my `fireplace-sound-file-path` variable with `C-h v` to locate the audio. When I visit the directory turns out that no fireplace.mp3 there. So I manualy download the audio from this repo and put it to the directory. Now the sound is working.
