### ISSUE TITLE
Instructions in README.md file don't work for me

### ISSUE THREAD

**Issue by randolf** [johanvts/emacs-fireplace#34]
I followed the instructions as best I could in the README.md file, and I managed to get things compiled to ~/.emacs/fireplace/fireplace.elc but I'm unable to get this working.

I have a fondness ASCII art and ANSI art, but I think my problem may be that I'm not familiar enough with emacs.  I'm using Debian 11 (Linux), and would love to get this running.  Thanks!

**Comment by johanvts** [comment]
It might be simpler to install from MELPA. You can follow the instructions here if you not familiar with MELPA: https://melpa.org/partials/getting-started.html
