### ISSUE TITLE
[Request] Adding in melpa repo please

### ISSUE THREAD

**Issue by thomas-louvigne** [johanvts/emacs-fireplace#5]
Thanks ;-)

**Comment by hut8** [comment]
Did it here:
https://github.com/milkypostman/melpa/pull/3403

**Comment by AdrieanKhisbe** [comment]
:+1:

**Comment by AdrieanKhisbe** [comment]
@zobi8225, tag a version so that stable is available too!

**Comment by thomas-louvigne** [comment]
@AdrieanKhisbe Sorry, i am a noob, what is a tag ?

**Comment by AdrieanKhisbe** [comment]
a git tag:

`git tag vX.Y.Z` :)

**Comment by hut8** [comment]
@AdrieanKhisbe the owner of the project is actually @johanvts , so he would be the one to ask for that :smile:

**Comment by AdrieanKhisbe** [comment]
ooops, my bad.haha

**Comment by johanvts** [comment]
Where should I tag what Again?

**Comment by AdrieanKhisbe** [comment]
84c5da2 as v0.2.0
, cf https://github.com/AdrieanKhisbe/emacs-fireplace/releases

**Comment by johanvts** [comment]
Thanks. I went ahead and tagged it as version 1.0, it's feature complete and pretty polished so I think it's justified :)
